routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');
Route::middleware(['auth'])->group(function()
{
	Route::resource('crud', 'CrudController');
	Route::resource('siswa', 'SiswaController');
});

app/Crud.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Crud extends Model
{
	protected $table 	= 'cruds';
	protected $fillable = ['kode_barang','nama_barang','harga'];
}

app/Kelas.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Kelas extends Model
{
	protected $table 	= 'kelas';
    protected $fillable = ['nama_kelas','slug_kelas'];
    public function siswas()
    {
        return $this->hasMany('App\Siswa');
    }
}

app/Siswa.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Siswa extends Model
{
	protected $table 	= 'siswas';
	protected $fillable = ['nis','nama','kelas_id'];

	public function kelas()
    {
        return $this->belongsTo('App\Kelas');
    }
}

app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Routing\Controller as BaseController;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Foundation\Auth\Access\AuthorizesRequests;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/CrudController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Crud;

class CrudController extends Controller
{
	/**
	 * Display a listing of the resource.
	 *
	 * @return \Illuminate\Http\Response
	 */
	public function index()
	{
		$crud = Crud::all();
		return view('crud.index', compact('crud'));
	}

	/**
	 * Show the form for creating a new resource.
	 *
	 * @return \Illuminate\Http\Response
	 */
	public function create()
	{
		return view('crud.create');
	}

	/**
	 * Store a newly created resource in storage.
	 *
	 * @param  \Illuminate\Http\Request  $request
	 * @return \Illuminate\Http\Response
	 */
	public function store(Request $request)
	{
		$data = $request->validate([
			'kode_barang' 	=> 'required|unique:cruds|max:255',
			'nama_barang' 	=> 'required',
			'harga' 		=> 'required',
		]);
		Crud::create($data);
		return redirect()->route('crud.index');
	}

	/**
	 * Display the specified resource.
	 *
	 * @param  int  $id
	 * @return \Illuminate\Http\Response
	 */
	public function show($id)
	{
		//
	}

	/**
	 * Show the form for editing the specified resource.
	 *
	 * @param  int  $id
	 * @return \Illuminate\Http\Response
	 */
	public function edit($id)
	{
		$crud = Crud::find($id);
		return view('crud.edit', compact('crud'));
	}

	/**
	 * Update the specified resource in storage.
	 *
	 * @param  \Illuminate\Http\Request  $request
	 * @param  int  $id
	 * @return \Illuminate\Http\Response
	 */
	public function update(Request $request, $id)
	{
		$data = $request->validate([
			'kode_barang' 	=> 'required',
			'nama_barang' 	=> 'required',
			'harga' 		=> 'required',
		]);
		Crud::find($id)->update($data);
		return redirect()->route('crud.index');
	}

	/**
	 * Remove the specified resource from storage.
	 *
	 * @param  int  $id
	 * @return \Illuminate\Http\Response
	 */
	public function destroy($id)
	{
		Crud::find($id)->delete();
		return redirect()->back();
	}
}

app/Http/Controllers/HomeController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class HomeController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * Show the application dashboard.
     *
     * @return \Illuminate\Contracts\Support\Renderable
     */
    public function index()
    {
        return view('home');
    }
}

app/Http/Controllers/SiswaController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Siswa;
use App\Kelas;

class SiswaController extends Controller
{
	/**
	 * Display a listing of the resource.
	 *
	 * @return \Illuminate\Http\Response
	 */
	public function index()
	{
		$siswas = Siswa::all();
		return view('siswa.index', compact('siswas'));
	}

	/**
	 * Show the form for creating a new resource.
	 *
	 * @return \Illuminate\Http\Response
	 */
	public function create()
	{
		$kelas = Kelas::all();
		return view('siswa.create', compact('kelas'));
	}

	/**
	 * Store a newly created resource in storage.
	 *
	 * @param  \Illuminate\Http\Request  $request
	 * @return \Illuminate\Http\Response
	 */
	public function store(Request $request)
	{
		$data = $request->validate([
			'nis' 		=> 'required|unique:siswas|max:8',
			'nama' 		=> 'required',
			'kelas_id' 	=> 'required',
		]);
		Siswa::create($data);
		return redirect()->route('siswa.index');
	}

	/**
	 * Display the specified resource.
	 *
	 * @param  int  $id
	 * @return \Illuminate\Http\Response
	 */
	public function show($id)
	{
		//
	}

	/**
	 * Show the form for editing the specified resource.
	 *
	 * @param  int  $id
	 * @return \Illuminate\Http\Response
	 */
	public function edit($id)
	{
		$siswa = Siswa::find($id);
		$kelas = Kelas::all();
		return view('siswa.edit', compact('siswa','kelas'));
	}

	/**
	 * Update the specified resource in storage.
	 *
	 * @param  \Illuminate\Http\Request  $request
	 * @param  int  $id
	 * @return \Illuminate\Http\Response
	 */
	public function update(Request $request, $id)
	{
		$data = $request->validate([
			'nis' 		=> 'required|max:8',
			'nama' 		=> 'required',
			'kelas_id' 	=> 'required',
		]);
		Siswa::find($id)->update($data);
		return redirect()->route('siswa.index');
	}

	/**
	 * Remove the specified resource from storage.
	 *
	 * @param  int  $id
	 * @return \Illuminate\Http\Response
	 */
	public function destroy($id)
	{
		Siswa::find($id)->delete();
		return redirect()->back();
	}
}

resources/views/crud/create.blade.php
@extends('layouts.app')

@push('styles')
	{{--  --}}
@endpush

@section('content')
<div class="container">
	<div class="row justify-content-center">
		<div class="col-md-8">
			<div class="card">
				<div class="card-header">Contoh CRUD</div>

				<div class="card-body">
					code crud di folder <code>resources/views/crud</code> <br><br><br>
					
					@if ($errors->any())
						<div class="alert alert-danger">
							<ul>
								@foreach ($errors->all() as $error)
									<li>{{ $error }}</li>
								@endforeach
							</ul>
						</div><br />
					@endif

					<form action="{{ route('crud.store') }}" method="POST">
						@csrf
						<div class="form-group">
							<label for="">Kode Barang</label>
							<input type="text" name="kode_barang" class="form-control" placeholder="Kode Barang">
						</div>
						<div class="form-group">
							<label for="">Nama Barang</label>
							<input type="text" name="nama_barang" class="form-control" placeholder="Nama Barang">
						</div>
						<div class="form-group">
							<label for="">Harga Barang</label>
							<input type="text" name="harga" class="form-control" placeholder="harga Barang">
						</div>
						<div class="form-group">
							<button type="submit" class="btn btn-primary">Simpan</button>
						</div>
					</form>
				</div>
			</div>
		</div>
	</div>
</div>
@endsection

@push('scripts')
	{{--  --}}
@endpush

resources/views/crud/edit.blade.php
@extends('layouts.app')

@push('styles')
	{{--  --}}
@endpush

@section('content')
<div class="container">
	<div class="row justify-content-center">
		<div class="col-md-8">
			<div class="card">
				<div class="card-header">Contoh CRUD</div>

				<div class="card-body">
					code crud di folder <code>resources/views/crud</code> <br><br><br>
					
					@if ($errors->any())
						<div class="alert alert-danger">
							<ul>
								@foreach ($errors->all() as $error)
									<li>{{ $error }}</li>
								@endforeach
							</ul>
						</div><br />
					@endif

					<form action="{{ route('crud.update', $crud->id) }}" method="POST">
						@csrf
						@method('PATCH')
						<div class="form-group">
							<label for="">Kode Barang</label>
							<input type="text" name="kode_barang" class="form-control" placeholder="Kode Barang" value="{{ $crud->kode_barang }}">
						</div>
						<div class="form-group">
							<label for="">Nama Barang</label>
							<input type="text" name="nama_barang" class="form-control" placeholder="Nama Barang" value="{{ $crud->nama_barang }}">
						</div>
						<div class="form-group">
							<label for="">Harga Barang</label>
							<input type="text" name="harga" class="form-control" placeholder="harga Barang" value="{{ $crud->harga }}">
						</div>
						<div class="form-group">
							<button type="submit" class="btn btn-primary">Simpan</button>
						</div>
					</form>
				</div>
			</div>
		</div>
	</div>
</div>
@endsection

@push('scripts')
	{{--  --}}
@endpush

resources/views/crud/index.blade.php
@extends('layouts.app')

@push('styles')
	<link rel="stylesheet" href="{{ asset('css/datatables.css') }}">
@endpush

@section('content')
<div class="container">
	<div class="row justify-content-center">
		<div class="col-md-8">
			<div class="card">
				<div class="card-header">Contoh CRUD</div>

				<div class="card-body">
					code crud di folder <code>resources/views/crud</code> <br><br><br>
					<a class="btn btn-info" href="{{ route('crud.create') }}">Tambah Data Crud</a> <br><br>
					<table id="crudtable" class="table table-striped table-bordered" style="width:100%">
						<thead>
							<tr>
								<th>No</th>
								<th>Kode Barang</th>
								<th>Nama Barang</th>
								<th>Harga</th>
								<th>Aksi</th>
							</tr>
						</thead>
						<tbody>
							@php
							$index = 1;
							@endphp
							@foreach($crud as $c)
							<tr>
								<td>{{ $index++ }}</td>
								<td>{{ $c->kode_barang }}</td>
								<td>{{ $c->nama_barang }}</td>
								<td>{{ $c->harga }}</td>
								<td>
									<form action="{{ route('crud.destroy', $c->id) }}" method="POST">
										@csrf
										@method('DELETE')
										<a class="btn btn-warning" href="{{ route('crud.edit', $c->id) }}">Edit</a> <button type="submit" class="btn btn-danger" onclick="return confirm('Yakin hapus data ini?')">Hapus</button>
									</form>
								</td>
							</tr>
							@endforeach
						</tbody>
						<tfoot>
							<tr>
								<th>No</th>
								<th>Kode Barang</th>
								<th>Nama Barang</th>
								<th>Harga</th>
								<th>Aksi</th>
							</tr>
						</tfoot>
					</table>
				</div>
			</div>
		</div>
	</div>
</div>
@endsection

@push('scripts')
	<script src="{{ asset('js/jquery.datatables.js') }}"></script>
	<script src="{{ asset('js/datatables.bs4.js') }}"></script>
	<script>
		$(document).ready(function() {
			$('#crudtable').DataTable({
				 "order": [[ 0, "desc" ]]
			});
		} );
	</script>
@endpush

resources/views/home.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">Dashboard</div>

                <div class="card-body">
                    @if (session('status'))
                        <div class="alert alert-success" role="alert">
                            {{ session('status') }}
                        </div>
                    @endif

                    You are logged in!
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/layouts/app.blade.php
<!DOCTYPE html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'Laravel') }}</title>

    <!-- Scripts -->

    <!-- Fonts -->
    <link rel="dns-prefetch" href="//fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css?family=Nunito" rel="stylesheet">

    <!-- Styles -->
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">
    @stack('styles')
</head>
<body>
    <div id="app">
        <nav class="navbar navbar-expand-md navbar-light bg-white shadow-sm">
            <div class="container">
                <a class="navbar-brand" href="{{ url('/') }}">
                    {{ config('app.name', 'Laravel') }}
                </a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="{{ __('Toggle navigation') }}">
                    <span class="navbar-toggler-icon"></span>
                </button>

                @include('layouts.nav')
            </div>
        </nav>

        <main class="py-4">
            @yield('content')
        </main>
    </div>
    <script src="{{ asset('js/jquery.js') }}"></script>
    <script src="{{ asset('js/app.js') }}" defer></script>
    @stack('scripts')
</body>
</html>

resources/views/layouts/nav.blade.php
<div class="collapse navbar-collapse" id="navbarSupportedContent">
	<!-- Left Side Of Navbar -->
	<ul class="navbar-nav mr-auto">
		<a href="{{ route('crud.index') }}" class="nav-link">Contoh CRUD</a>
		<a href="{{ route('siswa.index') }}" class="nav-link">Contoh Pluck</a>
	</ul>

	<!-- Right Side Of Navbar -->
	<ul class="navbar-nav ml-auto">
		<!-- Authentication Links -->
		@guest
			<li class="nav-item">
				<a class="nav-link" href="{{ route('login') }}">{{ __('Login') }}</a>
			</li>
			@if (Route::has('register'))
				<li class="nav-item">
					<a class="nav-link" href="{{ route('register') }}">{{ __('Register') }}</a>
				</li>
			@endif
		@else
			<li class="nav-item dropdown">
				<a id="navbarDropdown" class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
					{{ Auth::user()->name }} <span class="caret"></span>
				</a>

				<div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
					<a class="dropdown-item" href="{{ route('logout') }}"
					   onclick="event.preventDefault();
									 document.getElementById('logout-form').submit();">
						{{ __('Logout') }}
					</a>

					<form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
						@csrf
					</form>
				</div>
			</li>
		@endguest
	</ul>
</div>

resources/views/siswa/create.blade.php
@extends('layouts.app')

@push('styles')
	{{--  --}}
@endpush

@section('content')
<div class="container">
	<div class="row justify-content-center">
		<div class="col-md-8">
			<div class="card">
				<div class="card-header">Contoh Pluck dengan data siswa dan kelas</div>

				<div class="card-body">
					code pluck() di folder <code>resources/views/siswa</code> <br><br><br>
					
					@if ($errors->any())
						<div class="alert alert-danger">
							<ul>
								@foreach ($errors->all() as $error)
									<li>{{ $error }}</li>
								@endforeach
							</ul>
						</div><br />
					@endif

					<form action="{{ route('siswa.store') }}" method="POST">
						@csrf
						<div class="form-group">
							<label for="">NIS Siswa</label>
							<input type="number" name="nis" class="form-control" placeholder="NIS Siswa">
						</div>
						<div class="form-group">
							<label for="">Nama Siswa</label>
							<input type="text" name="nama" class="form-control" placeholder="Nama Siswa">
						</div>
						<div class="form-group">
							<label for="">Kelas</label>
							<select name="kelas_id" class="form-control">
								<option value="">pilih salah satu</option>
								@foreach($kelas as $k)
								<option value="{{ $k->id }}">{{ $k->nama_kelas }}</option>
								@endforeach
							</select>
						</div>
						<div class="form-group">
							<button type="submit" class="btn btn-primary">Simpan</button>
						</div>
					</form>
				</div>
			</div>
		</div>
	</div>
</div>
@endsection

@push('scripts')
	{{--  --}}
@endpush

resources/views/siswa/edit.blade.php
@extends('layouts.app')

@push('styles')
	{{--  --}}
@endpush

@section('content')
<div class="container">
	<div class="row justify-content-center">
		<div class="col-md-8">
			<div class="card">
				<div class="card-header">Contoh Pluck dengan data siswa dan kelas</div>

				<div class="card-body">
					code pluck() di folder <code>resources/views/siswa</code> <br><br><br>
					
					@if ($errors->any())
						<div class="alert alert-danger">
							<ul>
								@foreach ($errors->all() as $error)
									<li>{{ $error }}</li>
								@endforeach
							</ul>
						</div><br />
					@endif

					<form action="{{ route('siswa.update', $siswa->id) }}" method="POST">
						@csrf
						@method('PATCH')
						<div class="form-group">
							<label for="">NIS Siswa</label>
							<input type="number" name="nis" class="form-control" placeholder="NIS Siswa" value="{{ $siswa->nis }}">
						</div>
						<div class="form-group">
							<label for="">Nama Siswa</label>
							<input type="text" name="nama" class="form-control" placeholder="Nama Siswa" value="{{ $siswa->nama }}">
						</div>
						<div class="form-group">
							<label for="">Kelas</label>
							<select name="kelas_id" class="form-control" value="{{ $siswa->kelas_id }}">
								@foreach($kelas as $k)
								<option value="{{ $k->id }}" {{ $siswa->kelas_id == $k['id'] ? 'selected="selected"' : '' }}>{{ $k->nama_kelas }}</option>
								@endforeach
							</select>
						</div>
						<div class="form-group">
							<button type="submit" class="btn btn-primary">Simpan</button>
						</div>
					</form>
				</div>
			</div>
		</div>
	</div>
</div>
@endsection

@push('scripts')
	{{--  --}}
@endpush

resources/views/siswa/index.blade.php
@extends('layouts.app')

@push('styles')
	<link rel="stylesheet" href="{{ asset('css/datatables.css') }}">
@endpush

@section('content')
<div class="container">
	<div class="row justify-content-center">
		<div class="col-md-8">
			<div class="card">
				<div class="card-header">Contoh Pluck dengan data siswa dan kelas</div>

				<div class="card-body">
					code pluck() di folder <code>resources/views/siswa</code> <br><br><br>
					<a class="btn btn-info" href="{{ route('siswa.create') }}">Tambah Data Crud</a> <br><br>
					<table id="siswatable" class="table table-striped table-bordered" style="width:100%">
						<thead>
							<tr>
								<th>No</th>
								<th>NIS</th>
								<th>Nama Siswa</th>
								<th>Kelas</th>
								<th>Aksi</th>
							</tr>
						</thead>
						<tbody>
							@php
							$index = 1;
							@endphp
							@foreach($siswas as $c)
							<tr>
								<td>{{ $index++ }}</td>
								<td>{{ $c->nis }}</td>
								<td>{{ $c->nama }}</td>
								<td>{{ $c->kelas->nama_kelas }}</td>
								<td>
									<form action="{{ route('siswa.destroy', $c->id) }}" method="POST">
										@csrf
										@method('DELETE')
										<a class="btn btn-warning" href="{{ route('siswa.edit', $c->id) }}">Edit</a> <button type="submit" class="btn btn-danger" onclick="return confirm('Yakin hapus data ini?')">Hapus</button>
									</form>
								</td>
							</tr>
							@endforeach
						</tbody>
						<tfoot>
							<tr>
								<th>No</th>
								<th>NIS</th>
								<th>Nama Siswa</th>
								<th>Kelas</th>
								<th>Aksi</th>
							</tr>
						</tfoot>
					</table>
				</div>
			</div>
		</div>
	</div>
</div>
@endsection

@push('scripts')
	<script src="{{ asset('js/jquery.datatables.js') }}"></script>
	<script src="{{ asset('js/datatables.bs4.js') }}"></script>
	<script>
		$(document).ready(function() {
			$('#siswatable').DataTable({
				 "order": [[ 0, "desc" ]]
			});
		} );
	</script>
@endpush